#!/bin/bash
# Repository creation script
# Generates APT repository metadata from .deb files

set -e

# Progress reporting
log() {
    echo "::log::level=$1,msg=$2" >&2
}

# Change to output directory
OUTPUT_DIR="${1:-/workspace/output}"
cd "$OUTPUT_DIR" || {
    log "error" "Failed to change to output directory: $OUTPUT_DIR"
    exit 1
}

log "info" "Creating APT repository in $OUTPUT_DIR"

# Check if there are any .deb files
DEB_COUNT=$(ls -1 *.deb 2>/dev/null | wc -l)
if [ "$DEB_COUNT" -eq 0 ]; then
    log "error" "No .deb files found in $OUTPUT_DIR"
    exit 1
fi

log "info" "Found $DEB_COUNT .deb packages"

# Create Packages file
log "info" "Generating Packages file"
dpkg-scanpackages . /dev/null > Packages || {
    log "error" "Failed to create Packages file"
    exit 1
}

# Compress Packages file
log "info" "Compressing Packages file"
gzip -9c Packages > Packages.gz || {
    log "error" "Failed to compress Packages file"
    exit 1
}

# Create Release file
log "info" "Generating Release file"

# Get architecture from first .deb file
ARCH=$(dpkg --info *.deb | grep "Architecture:" | head -1 | awk '{print $2}')

cat > Release << EOF
Origin: colcon-deb
Label: colcon-deb
Suite: stable
Codename: stable
Version: 1.0
Architectures: $ARCH
Components: main
Description: ROS packages built with colcon-deb
Date: $(date -R)
EOF

# Add checksums to Release file
echo "MD5Sum:" >> Release
for file in Packages Packages.gz; do
    if [ -f "$file" ]; then
        SIZE=$(stat -c%s "$file")
        MD5=$(md5sum "$file" | awk '{print $1}')
        printf " %s %16d %s\n" "$MD5" "$SIZE" "$file" >> Release
    fi
done

echo "SHA256:" >> Release
for file in Packages Packages.gz; do
    if [ -f "$file" ]; then
        SIZE=$(stat -c%s "$file")
        SHA256=$(sha256sum "$file" | awk '{print $1}')
        printf " %s %16d %s\n" "$SHA256" "$SIZE" "$file" >> Release
    fi
done

# Use apt-ftparchive if available for more complete Release file
if command -v apt-ftparchive >/dev/null 2>&1; then
    log "info" "Enhancing Release file with apt-ftparchive"
    apt-ftparchive release . > Release.new && mv Release.new Release || {
        log "warning" "apt-ftparchive failed, using basic Release file"
    }
fi

# Create repository structure
log "info" "Creating repository directory structure"
mkdir -p dists/stable/main/binary-$ARCH
mv Packages* dists/stable/main/binary-$ARCH/
cp Release dists/stable/

# Create pool directory and move .deb files
mkdir -p pool/main
mv *.deb pool/main/

# Create a simple index.html for web browsing
cat > index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>colcon-deb Repository</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #333; }
        .info { background-color: #f0f0f0; padding: 10px; border-radius: 5px; }
        pre { background-color: #f5f5f5; padding: 15px; border-radius: 5px; overflow-x: auto; }
        .packages { margin-top: 20px; }
        .package { margin: 5px 0; }
    </style>
</head>
<body>
    <h1>colcon-deb APT Repository</h1>
    <div class="info">
        <h2>Usage</h2>
        <p>To use this repository, add the following to your APT sources:</p>
        <pre>
# Add to /etc/apt/sources.list.d/colcon-deb.list
deb [trusted=yes] file:///path/to/this/repo stable main

# Or for HTTP access:
# deb [trusted=yes] http://your-server/path/to/repo stable main

# Update package list
sudo apt update

# Install packages
sudo apt install ros-${ROS_DISTRO}-your-package
        </pre>
    </div>
    <div class="packages">
        <h2>Available Packages</h2>
        <ul>
EOF

# List all .deb files in the pool
for deb in pool/main/*.deb; do
    if [ -f "$deb" ]; then
        basename=$(basename "$deb")
        echo "            <li class=\"package\"><a href=\"$deb\">$basename</a></li>" >> index.html
    fi
done

cat >> index.html << 'EOF'
        </ul>
    </div>
    <div class="info">
        <p><small>Generated by colcon-deb on $(date)</small></p>
    </div>
</body>
</html>
EOF

# Create sources.list snippet
cat > colcon-deb.list << EOF
# colcon-deb repository
# Copy this file to /etc/apt/sources.list.d/
deb [trusted=yes] file://$OUTPUT_DIR stable main
EOF

# Summary
log "info" "Repository creation complete"
log "info" "Repository structure:"
find . -type f -name "*.gz" -o -name "Release" -o -name "*.deb" | head -20

log "info" "To use this repository locally:"
log "info" "  sudo cp colcon-deb.list /etc/apt/sources.list.d/"
log "info" "  sudo apt update"